#!/usr/bin/env python3
"""
generate_table.py

Reads platforms.json and generates COMPARISON.md.

Platforms are ROWS, features are COLUMNS.
Platforms are grouped by category with a separator between each group.

Usage:
    python generate_table.py
"""

import json
from pathlib import Path
from collections import defaultdict

INPUT_FILE  = Path("platforms.json")
OUTPUT_FILE = Path("COMPARISON.md")

EMOJI_MAP = {
    "yes":     "✅",
    "no":      "❌",
    "partial": "⚠️",
    "planned": "🗓️",
    "unknown": "❓",
}

def render_value(value: str) -> str:
    return EMOJI_MAP.get(value.lower(), "❓")

def build_full_table(categories: list, grouped: dict, features: list) -> list:
    """
    Build one large table where:
      - Each ROW is a platform
      - Each COLUMN is a feature
      - Platforms are grouped with a bold category label row between groups
    """
    lines = []

    # ── Column headers ──────────────────────────────────────────────────────
    # First two columns: Platform name + Description
    # Then one column per feature
    feature_labels = [f["label"] for f in features]

    header_cells = ["**Platform**", "**Description**", "**Architecture**"] + \
                   [f"**{lbl}**" for lbl in feature_labels]
    separator     = ["---"] * len(header_cells)

    lines.append("| " + " | ".join(header_cells) + " |")
    lines.append("| " + " | ".join(separator)     + " |")

    # ── One group at a time ──────────────────────────────────────────────────
    for category in categories:
        cat_platforms = grouped.get(category, [])
        if not cat_platforms:
            continue

        # Category label row — spans all columns using bold text in first cell
        spacers = [""] * (len(header_cells) - 1)
        lines.append(
            "| **" + category + "** | " +
            " | ".join(spacers) + " |"
        )

        # One row per platform
        for p in cat_platforms:
            name_cell = f"[{p['name']}]({p['url']})"
            desc_cell = p.get("description", "")
            arch_cell = p.get("architecture", "")

            feature_cells = []
            for f in features:
                fkey  = f["key"]
                raw   = p["features"].get(fkey, "unknown")
                emoji = render_value(raw)
                note  = p.get("feature_notes", {}).get(fkey, "")
                if note:
                    emoji += " †"
                feature_cells.append(emoji)

            all_cells = [name_cell, desc_cell, arch_cell] + feature_cells
            lines.append("| " + " | ".join(all_cells) + " |")

    return lines


def build_notes_section(categories: list, grouped: dict) -> list:
    """Collect all feature_notes across all platforms into a notes section."""
    lines = []
    any_notes = False

    for category in categories:
        cat_platforms = grouped.get(category, [])
        for p in cat_platforms:
            notes = p.get("feature_notes", {})
            if notes:
                if not any_notes:
                    lines.append("## † Notes")
                    lines.append("")
                    any_notes = True
                lines.append(f"**{p['name']}**")
                for fkey, note_text in notes.items():
                    label = fkey.replace("_", " ").title()
                    lines.append(f"- *{label}:* {note_text}")
                lines.append("")

    return lines


def main():
    data      = json.loads(INPUT_FILE.read_text(encoding="utf-8"))
    features  = data["features"]
    platforms = data["platforms"]
    categories = data["categories"]

    grouped = defaultdict(list)
    for p in platforms:
        grouped[p["category"]].append(p)

    lines = []

    # ── File header ──────────────────────────────────────────────────────────
    lines += [
        "# 📊 Platform Comparison",
        "",
        "> **Auto-generated from `platforms.json`** — do not edit this file directly.",
        "> To update, edit `platforms.json` and re-run `python generate_table.py`",
        "> (or push to main — the GitHub Action will regenerate it automatically).",
        "",
        "Platforms are grouped by type. Scroll right to see all feature columns.",
        "",
        "## Legend",
        "",
        "| Symbol | Meaning |",
        "|---|---|",
        "| ✅ | Fully supported |",
        "| ⚠️ | Partial / limited |",
        "| 🗓️ | Planned |",
        "| ❌ | Not supported |",
        "| ❓ | Unknown |",
        "| † | See notes section below |",
        "",
        "---",
        "",
        "## Comparison Table",
        "",
    ]

    # ── Main table ────────────────────────────────────────────────────────────
    lines += build_full_table(categories, grouped, features)
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Notes section ─────────────────────────────────────────────────────────
    lines += build_notes_section(categories, grouped)

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        "---",
        "",
        "## 🤝 Contributing",
        "",
        "See an error or missing platform? Edit `platforms.json` and open a Pull Request.",
        "See [CONTRIBUTING.md](CONTRIBUTING.md) for guidelines.",
        "",
    ]

    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"✅ Generated {OUTPUT_FILE} — "
        f"{len(platforms)} platforms × {len(features)} features "
        f"across {len(categories)} categories."
    )

if __name__ == "__main__":
    main()
